title: Mike Doyle
logo: /assets/img/headshot_circle.png
description: Hello, my name is Mike. Please contact me either through Email or DM on LinkedIn
show_downloads: true
theme: jekyll-theme-minimal




