title: Mike Doyle
logo: /assets/img/headshot_circle.png
description: 6+ years of corporate accounting & technical experience. In pursuit of my bachelor's degree in software engineering. Please feel free to contact me by email or DM on LinkedIn.
show_downloads: true
theme: jekyll-theme-minimal




